// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Self-hosted PostgREST endpoint and JWT secret
const SUPABASE_URL = "https://trserver.cloud";
const SUPABASE_PUBLIC_KEY = "504b96859cf48ca08981d49baa206506ccf71673078b6763d66fc1afd19e25cb"; // Must match PostgREST's JWT secret

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLIC_KEY);
